plugins {
    id 'org.springframework.boot' version '4.0.3'
    id 'io.spring.dependency-management' version '1.1.7'
    id 'java'
    id "name.remal.sonarlint" version "7.0.1"
    id "com.github.jakemarsden.git-hooks" version "0.0.2"
    id 'org.liquibase.gradle' version '2.2.2'
    id "co.uzzu.dotenv.gradle" version "4.0.0"
    id "jacoco"
    id 'org.barfuin.gradle.jacocolog' version '3.1.0'
}

group = 'com.waltsoft'
version = '0.0.1'
description = 'Spring AI Task Manager: A natural language interface for daily To-Do management, using AI Function Calling to trigger local CRUD operations.'


java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    enabled = false
}

repositories {
    mavenCentral()
    maven { url 'https://repo.spring.io/release' }
    maven { url 'https://repo.spring.io/milestone' }
}

dependencies {

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-aop:4.0.0-M2'

    implementation 'org.liquibase:liquibase-core:4.30.0'
    implementation 'org.hibernate.orm:hibernate-core:6.5.3.Final'
    implementation 'org.postgresql:postgresql:42.7.10'
    implementation 'io.github.cdimascio:java-dotenv:5.2.2'

    implementation 'info.picocli:picocli-spring-boot-starter:4.7.5'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.mockito:mockito-core:5.14.2'
    testImplementation 'org.testcontainers:junit-jupiter:1.20.4'
    testImplementation 'org.testcontainers:postgresql:1.20.4'
}

test {
    useJUnitPlatform()
    testLogging {
        exceptionFormat = 'full'
        events "passed", "skipped", "failed"
        showStandardStreams = (System.getenv('DEBUG') != null)
    }

    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = false
        csv.required = false
        html.outputLocation = layout.buildDirectory.dir('jacocoHtml')
    }
}

jacocoTestCoverageVerification {

    violationRules {
        rule {
            element = 'BUNDLE'
            limit {
                counter = 'CLASS'
                minimum = 0
            }
        }

        rule {
            element = 'BUNDLE'
            limit {
                counter = 'LINE'
                minimum = 0
            }
        }

    }
}

sonarLint {
    ignoreFailures = false
}

tasks.named('check') {
    dependsOn 'sonarlintMain'
    dependsOn 'jacocoTestCoverageVerification'
}

gitHooks {
    hooks = ['pre-commit': 'check']
}
