--liquibase formatted sql
--changeset walter.azvdo:make-task-category-status-priority-tables context:new splitStatements:true endDelimiter:;

CREATE TABLE task_status
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    code       TEXT NOT NULL,
    CONSTRAINT task_status_pk PRIMARY KEY (id),
    CONSTRAINT task_status_uk UNIQUE (code)
);

CREATE TABLE task_category
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    code       TEXT NOT NULL,
    CONSTRAINT task_category_pk PRIMARY KEY (id),
    CONSTRAINT task_category_uk UNIQUE (code)
);

CREATE TABLE task_priority
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    code       TEXT NOT NULL,
    CONSTRAINT task_priority_pk PRIMARY KEY (id),
    CONSTRAINT task_priority_uk UNIQUE (code)
);


CREATE TABLE task
(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP   NOT NULL DEFAULT NOW(),
    task_status_id BIGINT NOT NULL,
    task_category_id BIGINT NOT NULL,
    task_priority_id BIGINT NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    start_date_time TIMESTAMP NOT NULL,
    end_date_time TIMESTAMP,
    CONSTRAINT task_pk PRIMARY KEY (id),
    CONSTRAINT task_status_id_fk FOREIGN KEY (task_status_id) REFERENCES task_status (id),
    CONSTRAINT task_category_id_fk FOREIGN KEY (task_category_id) REFERENCES task_category (id),
    CONSTRAINT task_priority_id_fk FOREIGN KEY (task_priority_id) REFERENCES task_priority (id),
);

CREATE TRIGGER task_update_updated_at_column
    BEFORE UPDATE
    ON task
    FOR EACH ROW
EXECUTE PROCEDURE update_updated_at_column();

--rollback DROP TABLE task
--rollback DROP TABLE task_status
--rollback DROP TABLE task_category
--rollback DROP TABLE task_priority